# Generated by Django 5.2.1 on 2025-07-31 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_categories_listings_comments_bids_user_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='listingPhotos'),
        ),
    ]
