# Generated by Django 5.2.1 on 2025-07-31 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listings_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bids',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='listings',
            options={'ordering': ['-date']},
        ),
    ]
