# Generated by Django 5.2.1 on 2025-07-31 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_rename_bids_bid_rename_categories_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='amount',
            field=models.FloatField(),
        ),
    ]
