# Generated by Django 5.2.1 on 2025-08-19 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_listing_winner_alter_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='photo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
